#!/usr/bin/env node
var platform = process.platform,
  path = require('path'),
  child_process = require('child_process'),
  fs = require('fs'),
  app_path = "";
if(!!process.platform.match(/darwin/)) {
  app_path = path.join(__dirname, 'LessWatch.app');
  // command from http://hints.macworld.com/article.php?story=20111226075701552
  var command = "osascript -e 'tell application \"System Events\" to make login item at end with properties " +
    "{path:\"" + app_path + "\", hidden:false}'";

  child_process.exec(command, function (error, stdout, stderr) {
      if (error !== null) {
        console.error('Install failed: ' + error);
        console.log('stdout: ' + stdout);
        console.log('stderr: ' + stderr);
        return 1;
      }
      else {
        console.log('Installed Successfully.');
        console.log('To uninstall, go to System Preferences -> Users & Groups -> Login Items -> select "LessWatch" and click "-".');
        return 0;
      }
  });
} else if(!!process.platform.match(/linux/)) {
  if(typeof(process.env.SUDO_UID) !== 'undefined') {
    console.error("Please do not run install as root.");
    return 1;
  }
  app_path = path.join(__dirname, "less-watch");
  fs.appendFile(process.env.HOME + "/.profile", "\n" + app_path + "&\n", function(err) {
      if(err) {
        console.error(err);
        return 1;
      } else {
        console.log("Done. Yay!");
      }
  });
}