#!/usr/bin/env node
var path = require('path'),
  exec = require('child_process').exec,
  app_path = path.join(__dirname, 'LessWatch.app'),
  command = "osascript -e 'tell application \"System Events\" to make login item at end with properties " +
    "{path:\"" + app_path + "\", hidden:false}'";
// command from http://hints.macworld.com/article.php?story=20111226075701552

exec(command, function (error, stdout, stderr) {
  if (error !== null) {
    console.error('Install failed: ' + error);
    console.log('stdout: ' + stdout);
    console.log('stderr: ' + stderr);
  }
  else {
    console.log('Installed Successfully.');
    console.log('To uninstall, go to System Preferences -> Users & Groups -> Login Items -> select "LessWatch" and click "-".');
  }
});